# Generated by Django 4.1.10 on 2023-09-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_followrelation_unique_relation_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="followrelation",
            name="unique_relation",
        ),
        migrations.RemoveConstraint(
            model_name="followrelation",
            name="cannot_follow_myself",
        ),
        migrations.AddConstraint(
            model_name="followrelation",
            constraint=models.UniqueConstraint(
                fields=("following_user", "followed_user"),
                name="unique_relation",
                violation_error_message="同じユーザーを複数回フォローすることはできません",
            ),
        ),
        migrations.AddConstraint(
            model_name="followrelation",
            constraint=models.CheckConstraint(
                check=models.Q(("following_user", models.F("followed_user")), _negated=True),
                name="cannot_follow_myself",
                violation_error_message="自分自身をフォローすることはできない",
            ),
        ),
    ]
